[build]
  publish = "."         # הקבצים הסטטיים נמצאים בתיקייה הראשית

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
